spring:
  cloud:
     gateway:
        discovery:
          locator:
            enabled: true 
                
        default-filters:
          - TokenRelay     
        routes:
           - id: catalog-product-review-service
             uri: lb://catalog-product-review-service
             predicates:
               - Path=/product-reviews/**
             filters:
               - RemoveRequestHeader=Cookie
               - name: Retry
                 args:
                   retries: 3
                   method: GET
                   backoff:
                    firstBackoff: 50ms
                    maxBackoff: 500ms               
           - id: catalog-product-service
             uri: lb://catalog-product-service
             predicates:
               - Path=/products/**
             filters:
                - RemoveRequestHeader=Cookie
                - name: Retry
                  args:
                   retries: 3
                   method: GET
                   backoff:
                    firstBackoff: 50ms
                    maxBackoff: 500ms               
           - id: order-service
             uri: lb://order-service
             predicates:
               - Path=/orders/**
             filters:
               - RemoveRequestHeader=Cookie
               - name: Retry
                 args:
                   retries: 3
                   method: GET
                   backoff:
                    firstBackoff: 50ms
                    maxBackoff: 500ms               
           - id: payment-service
             uri: lb://payment-service
             predicates:
               - Path=/payments/**
             filters:
               - RemoveRequestHeader=Cookie
               - name: Retry
                 args:
                   retries: 3
                   method: GET
                   backoff:
                    firstBackoff: 50ms
                    maxBackoff: 500ms               
           - id: shipping-service
             uri: lb://shipping-service
             predicates:
               - Path=/shippings/**
             filters:
               - RemoveRequestHeader=Cookie
               - name: Retry
                 args:
                   retries: 3
                   method: GET
                   backoff:
                    firstBackoff: 50ms
                    maxBackoff: 500ms               
           - id: user-service
             uri: lb://user-service
             predicates:
               - Path=/users/**
             filters:
               - RemoveRequestHeader=Cookie
               - name: Retry
                 args:
                   retries: 3
                   method: GET
                   backoff:
                    firstBackoff: 50ms
                    maxBackoff: 500ms               

           - id: openapi
             uri: 'http://localhost:${server.port}'
             predicates:
                - Path=/v3/api-docs/**
             filters:
               - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs                
  security:
    oauth2:
      client:
        provider:
          keycloak:
            token-uri: http://localhost:8888/auth/realms/SpringBootKeycloak/protocol/openid-connect/token
            authorization-uri: http://localhost:8888/auth/realms/SpringBootKeycloak/protocol/openid-connect/auth
            user-info-uri: http://localhost:8888/auth/realms/SpringBootKeycloak/protocol/openid-connect/userinfo
            user-name-attribute: preferred_username
            jwk-set-uri: http://localhost:8888/auth/realms/SpringBootKeycloak/protocol/openid-connect/certs 
        registration:
          springboot-microservice:
            provider: keycloak
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/springboot-microservice"               

   