spring:
  output:
    ansi:
      enabled: never
  cloud:
    stream:
      source: notificationEventSupplier
      bindings:
        notificationEventSupplier-out-0:
          destination: notification-events 
        notificationEventSupplier-in-0:
          destination: notification-events           

#Configuração para rodar local
eureka:
  client:
     register-with-eureka: true
     fetch-registry: true
     service-url:
       defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    instance-id: ${spring.name.application}:${random.uuid}

#Configuração K8S
#eureka:
#  instance:
#    preferIpAddress: true
#    hostname: eureka-0
#  client:
#    registerWithEureka: true
#    fetchRegistry: true
#    serviceUrl:
#      defaultZone: http://eureka-0.eureka.default.svc.cluster.local:8761/eureka
    
info:
  app:
    encoding: "@project.build.sourceEncoding@"
    java:
      source: "@java.version@"
      target: "@java.version@"    
