management:
  endpoints:
    jmx:
      exposure:
        include: "health,info"  
    web:
      exposure:
        include: "*"
  info:
    git:
      mode: "full"
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8888/auth/realms/SpringBootKeycloak
logging:
    level:
        org:
            springframework:
                security: DEBUG        
                cloud:
                  gateway: DEBUG
                http:
                  server:
                    reactive: DEBUG
                web:
                  reactive: DEBUG      
