management:
  health:
     circuitbreakers:
        enabled: true
  endpoints:
    jmx:
      exposure:
        include: "health,info"  
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always        
  info:
    git:
      mode: "full"
spring:
  rabbitmq:
    host: localhost
    port: 15672
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8888/auth/realms/SpringBootKeycloak
logging:
    level:
        org:
            springframework:
                security: DEBUG        
                cloud:
                  gateway: DEBUG
                http:
                  server:
                    reactive: DEBUG
                web:
                  reactive: DEBUG      
                  servlet:
                      DispatcherServlet: DEBUG                                    
                  

