spring:
  output:
    ansi:
      enabled: never
eureka:
  client:
     register-with-eureka: true
     fetch-registry: true
     service-url:
       defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    
info:
  app:
    encoding: "@project.build.sourceEncoding@"
    java:
      source: "@java.version@"
      target: "@java.version@"    
