management:
  health:
     circuitbreakers:
        enabled: true
  endpoints:
    jmx:
      exposure:
        include: "health,info"  
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always        
  info:
    git:
      mode: "full"
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8888/auth/realms/SpringBootKeycloak

logging:
    level:
        org:
            springframework:
                security: INFO
                cloud:
                  gateway: INFO
                http:
                  server:
                    reactive: INFO
                web:
                  reactive: INFO      
