management:
  endpoints:
    jmx:
      exposure:
        include: "health,info"  
    web:
      exposure:
        include: "*"
  info:
    git:
      mode: "full"
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8888/auth/realms/master
